### ISSUE TITLE
Use activeMQ and apache-camel in project

### ISSUE THREAD

**Issue by mAdloVe** [JMaNGOS/JMaNGOS#35]
![35](https://f.cloud.github.com/assets/914622/1143375/daa60d56-1d37-11e3-884a-f1e1b4da0f6f.jpg)

**Comment by mAdloVe** [comment]
![35_1](https://f.cloud.github.com/assets/914622/1143389/8361630a-1d38-11e3-8f13-75e339279c1f.jpg)

**Comment by mAdloVe** [comment]
![35_2](https://f.cloud.github.com/assets/914622/1143392/ccee0b04-1d38-11e3-97e3-c8d86ddae007.jpg)

**Comment by mAdloVe** [comment]
![35_3](https://f.cloud.github.com/assets/914622/1143397/0821c2f6-1d39-11e3-819e-8cc47f4a7958.jpg)

**Comment by mAdloVe** [comment]
![35_4](https://f.cloud.github.com/assets/914622/1143415/72d33326-1d3b-11e3-8409-da7f26ee5646.jpg)

**Comment by mAdloVe** [comment]
![35_5](https://f.cloud.github.com/assets/914622/1143417/b9b19666-1d3b-11e3-8a87-21a58e7c2585.jpg)

**Comment by mAdloVe** [comment]
![35_6](https://f.cloud.github.com/assets/914622/1143445/4506398c-1d3d-11e3-8e2e-8779ea34d4ca.jpg)

**Comment by mAdloVe** [comment]
![35_7](https://f.cloud.github.com/assets/914622/1143424/5f5bc15e-1d3c-11e3-86b7-66c5ef1f00fd.jpg)

**Comment by mAdloVe** [comment]
![35_8](https://f.cloud.github.com/assets/914622/1143435/c843ef66-1d3c-11e3-9ad4-08166c70c01e.jpg)

**Comment by ZuSe** [comment]
You should just use the message broker of your target container ;)

**Comment by mAdloVe** [comment]
used apache-camel
