### ISSUE TITLE
Can not open website: http://jmangos.org/

### ISSUE THREAD

**Issue by geektcp** [JMaNGOS/JMaNGOS#41]
I m Chinese, the website cannot open it .
I can open google.com, any other website

**Comment by gibson** [comment]
This site don't working already 5 years

**Comment by geektcp** [comment]
I have a idle server  , maybe deploy this website, ok ?

**Comment by geektcp** [comment]
> This site don't working already 5 years

I have a idle server , maybe deploy this website? Let's revive it, r u interested?
