### ISSUE TITLE
Migrating from Guice to Spring

### ISSUE THREAD

**Issue by mAdloVe** [JMaNGOS/JMaNGOS#6]
http://forum.jmangos.org/viewtopic.php?f=7&t=22

**Comment by mAdloVe** [comment]
![6](https://f.cloud.github.com/assets/914622/1143636/8a615b8c-1d4d-11e3-9fc6-0baf2e0eed34.jpg)

**Comment by ZuSe** [comment]
Btw why are using Spring instead of JavaEE 7?
Wouldn't JavaEE 7 fit more for a wow core than spring, which was primaly developed for web applications?

**Comment by mAdloVe** [comment]
Is it accidentally JavaEE more intended for web applications?

**Comment by ZuSe** [comment]
Checkout this:
http://www.theserverside.com/discussions/thread.tss?thread_id=61023

He gives a really good explanation why there is no need for spring these days.
